commite practical 2
mrHouvis/NCTaskManager pull request #2
Opened 2020-11-11 11:16 UTC by mrHouvis

2020-11-11 11:28 UTC, Berya1988 requested changes

2020-11-11 11:28 UTC, Berya1988 commented on src/main/java/ua/edu/sumdu/j2se/shelekhovDenis/tasks/ArrayTaskList.java
> +    ArrayList<Task> arrayList = new ArrayList<>();
Нельзя использовать готовую коллекцию, нужно на основе массива

2020-11-11 11:31 UTC, mrHouvis commented on src/main/java/ua/edu/sumdu/j2se/shelekhovDenis/tasks/ArrayTaskList.java
> +    ArrayList<Task> arrayList = new ArrayList<>();
понял, сделаю

2020-11-11 14:56 UTC, mrHouvis commented
у меня вопрос, что проверяется в этом тесте?
[image: image.png]
я просто понять не могу, как у меня остальные работают, а здесь элементов в
массиве получается меньше чем надо

ср, 11 нояб. 2020 г. в 14:29, Берест Олег Борисович <
notifications@github.com>:

> *@Berya1988* requested changes on this pull request.
> ------------------------------
>
> In src/main/java/ua/edu/sumdu/j2se/shelekhovDenis/tasks/ArrayTaskList.java
> <https://github.com/mrHouvis/NCTaskManager/pull/2#discussion_r521293545>:
>
> > @@ -0,0 +1,42 @@
>
> +package ua.edu.sumdu.j2se.shelekhovDenis.tasks;
>
> +
>
> +import java.util.ArrayList;
>
> +
>
> +public class ArrayTaskList {
>
> +
>
> +    ArrayList<Task> arrayList = new ArrayList<>();
>
>
> Нельзя использовать готовую коллекцию, нужно на основе массива
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mrHouvis/NCTaskManager/pull/2#pullrequestreview-528089195>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARNXVPRYZ44MCEV4MMFF7O3SPJYQNANCNFSM4TR3TP7Q>
> .
>

2020-11-19 07:01 UTC, Berya1988 requested changes

2020-11-19 07:01 UTC, Berya1988 commented on src/main/java/ua/edu/sumdu/j2se/shelekhovDenis/tasks/ArrayTaskList.java
> +    Task[] taskList = {null};
Плохой подход, делай завязку сразу на N (=10) елементов, а в методе add учитывай это

2020-11-19 07:01 UTC, Berya1988 commented on src/main/java/ua/edu/sumdu/j2se/shelekhovDenis/tasks/ArrayTaskList.java
> +            Task[] taskListTemp = new Task[taskList.length + 1];
увеличивай сразу в 1.5 раза, по +1  - неоправданно

2020-11-20 17:13 UTC, Berya1988 approved these changes

2020-11-21 08:32 UTC, merged